### PR TITLE
Swedish: Initial commit

### PR DESCRIPTION
**Pull request by EDALJO**
I took the liberty of translating the website into Swedish. I'm struggling with some Jinja exceptions, so I haven't been able to successfully build the project yet. If there are some known tricks other than cleaning the cache, please let me know.

### CODE REVIEW

**Comment by humenda** [comment]
Thanks! Already online.

**Comment by EDALJO** [comment]
> Thanks! Already online.

Cheers! It seems, however, as if everything but the top bar and some content is in English. Is it just pointing to the wrong contents, perhaps?

**Comment by humenda** [comment]
Well, the generation took a while since I needed to install the sv locale :).
Should be fine now.

**Comment by EDALJO** [comment]
> Well, the generation took a while since I needed to install the sv locale :). Should be fine now.

Got it! Found some erroneous formatting when glancing through my changes, I'll try to raise another PR for fixing those as soon as I have time.

**Pull request closed without merging**
